development:
  hosts: 
   - '127.0.0.1'
  port: 9042
  keyspace: samples_cassandra_test_development
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: NetworkTopologyStrategy
    datacenter1: 2
  durable_writes: false

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: samples_cassandra_test_test
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  hosts:
    - 'cass1.samples_cassandra_test.biz'
    - 'cass2.samples_cassandra_test.biz'
    - 'cass3.samples_cassandra_test.biz'
  port: 9042
  keyspace: samples_cassandra_test_production
  username: 'myappuser'
  password: 'password1'
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: SimpleStrategy
    replication_factor: 1
# replication:
#   class: NetworkTopologyStrategy
#   datacenter1: 3
#   datacenter2: 2
# durable_writes: false
